import Company from '../types/Company';
export const companies: Company[] = [
  {
    id: 1,
    companyName: 'MusicStore GmbH',
    companyNr: '83742738',
    deleted: false,
    emailAddress: 'musicstore@getMaxListeners.com',
    fax: '0123-456781',
    firstName: 'Max',
    lastName: 'Mustermann',
    phone: '0123-456780',
    addressList: [
      {
        city: 'Musterhausen',
        country: 'Germany',
        postCode: '34336',
        street: 'Waldstraße 2',
        addressType: 'main',
      },
      {
        city: 'Eppingen',
        country: 'Germany',
        postCode: '55748',
        street: 'Steingasse 88',
        addressType: 'post',
      },
    ],
  },
  {
    id: 2,
    companyName: 'Thomann GmbH & Co KG',
    companyNr: '47563223',
    deleted: false,
    emailAddress: 'thomann@posteo.de',
    fax: '0223-888998',
    firstName: 'John',
    lastName: 'Doe',
    phone: '0223-888999',
    addressList: [
      {
        city: 'München',
        country: 'Germany',
        postCode: '34336',
        street: 'Waldstraße 2',
        addressType: 'main',
      },
      {
        city: 'Eppingen',
        country: 'Germany',
        postCode: '55748',
        street: 'Steingasse 88',
        addressType: 'post',
      },
    ],
  },
  {
    id: 3,
    companyName: 'Thomann GmbH & Co KG',
    companyNr: '47563223',
    deleted: false,
    emailAddress: 'thomann@posteo.de',
    fax: '0223-888998',
    firstName: 'John',
    lastName: 'Doe',
    phone: '0223-888999',
    addressList: [
      {
        city: 'München',
        country: 'Germany',
        postCode: '34336',
        street: 'Waldstraße 2',
        addressType: 'main',
      },
      {
        city: 'Eppingen',
        country: 'Germany',
        postCode: '55748',
        street: 'Steingasse 88',
        addressType: 'post',
      },
    ],
  },
  {
    id: 4,
    companyName: 'Thomann GmbH & Co KG',
    companyNr: '47563223',
    deleted: false,
    emailAddress: 'thomann@posteo.de',
    fax: '0223-888998',
    firstName: 'John',
    lastName: 'Doe',
    phone: '0223-888999',
    addressList: [
      {
        city: 'München',
        country: 'Germany',
        postCode: '34336',
        street: 'Waldstraße 2',
        addressType: 'main',
      },
      {
        city: 'Eppingen',
        country: 'Germany',
        postCode: '55748',
        street: 'Steingasse 88',
        addressType: 'post',
      },
    ],
  },
];
